# Generated by Django 4.1.7 on 2023-03-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('stationary', 'stationary'), ('Electronic', 'Electronic'), ('Food', 'Food')], max_length=30, null=True)),
                ('quantity', models.PositiveIntegerField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
    ]
